// client_v2/src/lib/components/NfcScannerModal.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import * as m from '$lib/paraglide/messages';
	import X from '@lucide/svelte/icons/x';
	import Loader from '@lucide/svelte/icons/loader-circle';
	import Button from './Button.svelte';
	import NfcModeSwitch from './NfcModeSwitch.svelte';
	import NfcNotice from './NfcNotice.svelte';
	import NfcTagSummary from './NfcTagSummary.svelte';
	import {
		isWebNfcSupported,
		nfcCreateFromTag,
		nfcRead,
		type QidiTagData,
		type TigerTagData
	} from '$lib/api/nfc';
	import { nfcState } from '$lib/stores/nfc.svelte';
	import { decodeTigerTag, isTigerTag } from '$lib/utils/tigertagCodec';

	interface Props {
		open: boolean;
		onclose?: () => void;
	}
	let { open, onclose }: Props = $props();

	let mode = $state<'server' | 'browser'>('server');
	let reading = $state(false);
	let readError = $state<string | null>(null);
	let readMessage = $state<string | null>(null);
	let browserScanning = $state(false);
	let browserError = $state<string | null>(null);
	let creating = $state(false);
	let createError = $state<string | null>(null);

	let unmatchedTagData = $state<TigerTagData | null>(null);
	let unmatchedQidiData = $state<QidiTagData | null>(null);
	let unmatchedTagUid = $state<string | null>(null);
	let unmatchedTagFormat = $state<string | null>(null);

	let webNfcAvailable = isWebNfcSupported();

	function resetState() {
		reading = false;
		readError = null;
		readMessage = null;
		browserScanning = false;
		browserError = null;
		creating = false;
		createError = null;
		unmatchedTagData = null;
		unmatchedQidiData = null;
		unmatchedTagUid = null;
		unmatchedTagFormat = null;
	}

	// Reset scan state each time the modal opens, and default to whichever mode
	// actually works — the segmented switch itself stays reachable either way so
	// a user with both can still flip it.
	$effect(() => {
		if (!open) return;
		resetState();
		mode = nfcState.serverEnabled ? 'server' : 'browser';
	});

	function close() {
		onclose?.();
	}

	async function handleServerRead() {
		resetState();
		reading = true;
		try {
			const result = await nfcRead();
			if (result.success && result.spool_id) {
				close();
				goto(resolve(`/?sel=spool:${result.spool_id}`));
				return;
			}
			if (result.success) {
				unmatchedTagFormat = result.tag_format ?? null;
				unmatchedTagUid = result.nfc_tag_uid ?? null;
				if (result.qidi_data) {
					unmatchedQidiData = result.qidi_data;
				} else if (result.tag_data) {
					unmatchedTagData = result.tag_data;
				} else {
					readMessage = result.message || m['nfc.noMatch']();
				}
			} else {
				readError = result.message || m['nfc.error.readFailed']();
			}
		} catch {
			readError = m['nfc.error.readFailed']();
		} finally {
			reading = false;
		}
	}

	async function handleBrowserScan() {
		if (!window.NDEFReader) {
			browserError = m['nfc.error.notSupported']();
			return;
		}

		browserScanning = true;
		browserError = null;
		unmatchedTagData = null;

		try {
			const reader = new window.NDEFReader();
			const controller = new AbortController();

			reader.onreading = (event) => {
				controller.abort();
				browserScanning = false;

				for (const record of event.message.records) {
					if (record.recordType === 'tigertag.io:maker' && record.data) {
						try {
							const tagData = decodeTigerTag(record.data.buffer as ArrayBuffer);
							if (isTigerTag(tagData.id_tigertag) && tagData.id_product > 0) {
								const colorHex = [tagData.color_r, tagData.color_g, tagData.color_b]
									.map((c) => c.toString(16).padStart(2, '0'))
									.join('');
								const diameterMm = tagData.id_diameter === 1 ? 1.75 : tagData.id_diameter === 2 ? 2.85 : 0;

								unmatchedTagData = {
									id_tigertag: tagData.id_tigertag,
									id_product: tagData.id_product,
									id_material: tagData.id_material,
									id_diameter: tagData.id_diameter,
									id_brand: tagData.id_brand,
									color_hex: colorHex,
									weight: tagData.weight,
									nozzle_temp: tagData.nozzle_temp,
									bed_temp: tagData.bed_temp,
									drying_temp: tagData.drying_temp,
									drying_duration: tagData.drying_duration,
									timestamp: tagData.timestamp,
									user_message: tagData.user_message,
									diameter_mm: diameterMm
								};
								return;
							}
						} catch {
							// Failed to decode, fall through to other record types
						}
					}

					if (record.recordType === 'url' || record.recordType === 'text') {
						const decoder = new TextDecoder(record.encoding || 'utf-8');
						const text = record.data ? decoder.decode(record.data) : '';

						const spoolmanMatch = text.match(/web\+spoolman:s-(\d+)/);
						if (spoolmanMatch) {
							close();
							goto(resolve(`/?sel=spool:${spoolmanMatch[1]}`));
							return;
						}

						const urlMatch = text.match(/\/spool\/show\/(\d+)/);
						if (urlMatch) {
							close();
							goto(resolve(`/?sel=spool:${urlMatch[1]}`));
							return;
						}
					}
				}

				browserError = m['nfc.noMatch']();
			};

			reader.onreadingerror = () => {
				controller.abort();
				browserScanning = false;
				browserError = m['nfc.error.readFailed']();
			};

			await reader.scan({ signal: controller.signal });
		} catch (error) {
			browserScanning = false;
			if (error instanceof DOMException && error.name === 'NotAllowedError') {
				browserError = m['nfc.error.permissionDenied']();
			} else {
				browserError = m['nfc.error.readFailed']();
			}
		}
	}

	async function handleCreateFromTag() {
		if (!unmatchedTagData && !unmatchedQidiData) return;
		creating = true;
		createError = null;
		try {
			const result =
				unmatchedQidiData && unmatchedTagFormat === 'qidi'
					? await nfcCreateFromTag({
							tag_type: 'qidi',
							material_code: unmatchedQidiData.material_code,
							color_code: unmatchedQidiData.color_code,
							nfc_tag_uid: unmatchedTagUid ?? undefined
						})
					: unmatchedTagData
						? await nfcCreateFromTag({
								id_product: unmatchedTagData.id_product,
								id_material: unmatchedTagData.id_material,
								id_diameter: unmatchedTagData.id_diameter,
								id_brand: unmatchedTagData.id_brand,
								color_hex: unmatchedTagData.color_hex,
								weight: unmatchedTagData.weight,
								nozzle_temp: unmatchedTagData.nozzle_temp,
								bed_temp: unmatchedTagData.bed_temp,
								drying_temp: unmatchedTagData.drying_temp,
								drying_duration: unmatchedTagData.drying_duration,
								diameter_mm: unmatchedTagData.diameter_mm
							})
						: null;

			if (result?.success && result.spool_id) {
				close();
				goto(resolve(`/?sel=spool:${result.spool_id}`));
				return;
			}
			createError = result?.message || m['nfc.error.createFailed']();
		} catch {
			createError = m['nfc.error.createFailed']();
		} finally {
			creating = false;
		}
	}

	let hasUnmatched = $derived(unmatchedTagData !== null || unmatchedQidiData !== null);
</script>

{#if open}
	<div
		class="overlay"
		role="button"
		tabindex="0"
		onclick={close}
		onkeydown={(e) => e.key === 'Escape' && close()}
	>
		<div
			class="modal"
			role="dialog"
			aria-modal="true"
			aria-label={m['nfc.scanTitle']()}
			tabindex="-1"
			onclick={(e) => e.stopPropagation()}
			onkeydown={(e) => e.stopPropagation()}
		>
			<div class="modal-head">
				<span class="title">{m['nfc.scanTitle']()}</span>
				<button class="x" onclick={close} aria-label={m['buttons.close']()}><X size={16} /></button>
			</div>

			<div class="body">
				<p class="hint">{m['nfc.scanDescription']()}</p>

				<NfcModeSwitch
					{mode}
					serverEnabled={nfcState.serverEnabled}
					browserEnabled={webNfcAvailable}
					serverLabel={m['nfc.modeServer']()}
					browserLabel={m['nfc.modeBrowser']()}
					onchange={(v) => (mode = v)}
				/>

				{#if !hasUnmatched}
					{#if mode === 'server'}
						<div class="stage">
							<Button onclick={handleServerRead} disabled={reading}>
								{#if reading}<Loader size={14} class="spin" />{/if}
								{reading ? m['nfc.reading']() : m['nfc.scanTitle']()}
							</Button>
							{#if readMessage}<NfcNotice kind="warning" message={readMessage} />{/if}
							{#if readError}<NfcNotice kind="error" message={readError} />{/if}
						</div>
					{:else}
						<div class="stage">
							<Button onclick={handleBrowserScan} disabled={browserScanning}>
								{#if browserScanning}<Loader size={14} class="spin" />{/if}
								{browserScanning ? m['nfc.placeTag']() : m['nfc.scanTitle']()}
							</Button>
							{#if browserError}<NfcNotice kind="error" message={browserError} />{/if}
						</div>
					{/if}
				{:else}
					<NfcNotice kind="info" message={m['nfc.createFromTagDescription']()} />
					<NfcTagSummary tagData={unmatchedTagData ?? undefined} qidiData={unmatchedQidiData ?? undefined} />
					<Button onclick={handleCreateFromTag} disabled={creating}>
						{creating ? m['nfc.creatingSpool']() : m['nfc.createFromTag']()}
					</Button>
					{#if createError}<NfcNotice kind="error" message={createError} />{/if}
				{/if}
			</div>
		</div>
	</div>
{/if}

<style>
	.overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.6);
		z-index: 50;
		display: flex;
		align-items: flex-start;
		justify-content: center;
		padding: 8vh 16px 16px;
	}
	.modal {
		width: 440px;
		max-width: 100%;
		display: flex;
		flex-direction: column;
		background: var(--bg);
		border: 1px solid var(--border-strong);
		border-radius: var(--radius-xl);
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6);
		overflow: hidden;
	}
	.modal-head {
		display: flex;
		align-items: center;
		gap: 10px;
		padding: 16px 20px 0;
		flex: none;
	}
	.title {
		font-weight: 700;
		font-size: 16px;
	}
	.x {
		margin-left: auto;
		color: var(--text-dim);
		cursor: pointer;
		font-size: 15px;
		padding: 4px 8px;
		background: none;
		border: none;
	}
	.x:hover {
		color: var(--text);
	}
	.hint {
		margin: 0;
		font-size: 12.5px;
		color: var(--text-muted);
	}
	.body {
		display: flex;
		flex-direction: column;
		gap: 14px;
		padding: 12px 20px 20px;
	}
	.stage {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 10px;
		padding: 20px 0;
	}
	:global(.spin) {
		animation: spin 1s linear infinite;
	}
	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>

// client/src/components/nfcScannerModal.tsx
import { WifiOutlined } from "@ant-design/icons";
import { useTranslate } from "@refinedev/core";
import { Alert, Button, Descriptions, FloatButton, Modal, Segmented, Space, Spin, Typography } from "antd";
import React, { useCallback, useState } from "react";
import { useNavigate } from "react-router";
import { QidiTagData, TigerTagData, isWebNfcSupported, useNfcCreateFromTag, useNfcRead, useNfcStatus } from "../utils/nfc";
import { decodeTigerTag, isTigerTag } from "../utils/tigertagCodec";

const { Text } = Typography;

/**
 * Renders decoded TigerTag data as a compact Descriptions panel.
 */
const TagDataSummary: React.FC<{ tagData: TigerTagData; t: (key: string) => string }> = ({ tagData, t }) => {
  const diameter =
    tagData.diameter_mm > 0
      ? `${tagData.diameter_mm} mm`
      : tagData.id_diameter === 1
        ? "1.75 mm"
        : tagData.id_diameter === 2
          ? "2.85 mm"
          : "—";

  return (
    <Descriptions column={2} size="small" bordered>
      <Descriptions.Item label={t("nfc.tag_color")}>
        {tagData.color_hex ? (
          <Space>
            <span
              style={{
                display: "inline-block",
                width: 16,
                height: 16,
                borderRadius: 3,
                backgroundColor: `#${tagData.color_hex}`,
                border: "1px solid #d9d9d9",
                verticalAlign: "middle",
              }}
            />
            #{tagData.color_hex}
          </Space>
        ) : (
          "—"
        )}
      </Descriptions.Item>
      <Descriptions.Item label={t("nfc.tag_diameter")}>{diameter}</Descriptions.Item>
      <Descriptions.Item label={t("nfc.tag_weight")}>
        {tagData.weight > 0 ? `${tagData.weight} g` : "—"}
      </Descriptions.Item>
      <Descriptions.Item label={t("nfc.tag_nozzle_temp")}>
        {tagData.nozzle_temp > 0 ? `${tagData.nozzle_temp} °C` : "—"}
      </Descriptions.Item>
      <Descriptions.Item label={t("nfc.tag_bed_temp")}>
        {tagData.bed_temp > 0 ? `${tagData.bed_temp} °C` : "—"}
      </Descriptions.Item>
    </Descriptions>
  );
};

/**
 * Renders decoded Qidi tag data as a compact Descriptions panel.
 */
const QidiTagDataSummary: React.FC<{ qidiData: QidiTagData; t: (key: string) => string }> = ({ qidiData, t }) => (
  <Descriptions column={2} size="small" bordered>
    <Descriptions.Item label={t("nfc.tag_format")}>Qidi</Descriptions.Item>
    <Descriptions.Item label={t("nfc.tag_material")}>{qidiData.material_name}</Descriptions.Item>
    <Descriptions.Item label={t("nfc.tag_color")}>
      {qidiData.color_hex ? (
        <Space>
          <span
            style={{
              display: "inline-block",
              width: 16,
              height: 16,
              borderRadius: 3,
              backgroundColor: `#${qidiData.color_hex}`,
              border: "1px solid #d9d9d9",
              verticalAlign: "middle",
            }}
          />
          {qidiData.color_name}
        </Space>
      ) : (
        "—"
      )}
    </Descriptions.Item>
    <Descriptions.Item label={t("nfc.tag_material_type")}>{qidiData.material_type}</Descriptions.Item>
  </Descriptions>
);

const NfcScannerModal: React.FC = () => {
  const [visible, setVisible] = useState(false);
  const [mode, setMode] = useState<"browser" | "server">("server");
  const [browserScanning, setBrowserScanning] = useState(false);
  const [browserError, setBrowserError] = useState<string | null>(null);
  const [unmatchedTagData, setUnmatchedTagData] = useState<TigerTagData | null>(null);
  const [unmatchedQidiData, setUnmatchedQidiData] = useState<QidiTagData | null>(null);
  const [unmatchedTagUid, setUnmatchedTagUid] = useState<string | null>(null);
  const [unmatchedTagFormat, setUnmatchedTagFormat] = useState<string | null>(null);
  const t = useTranslate();
  const navigate = useNavigate();

  const nfcStatus = useNfcStatus();
  const nfcReadMutation = useNfcRead();
  const createFromTagMutation = useNfcCreateFromTag();

  const serverEnabled = nfcStatus.data?.enabled === true && nfcStatus.data?.status === "connected";
  const webNfcAvailable = isWebNfcSupported();

  const handleServerRead = useCallback(async () => {
    setUnmatchedTagData(null);
    setUnmatchedQidiData(null);
    setUnmatchedTagUid(null);
    setUnmatchedTagFormat(null);
    const result = await nfcReadMutation.mutateAsync();
    if (result.success && result.spool_id) {
      setVisible(false);
      navigate(`/spool/show/${result.spool_id}`);
    } else if (result.success && !result.spool_id) {
      setUnmatchedTagFormat(result.tag_format || null);
      setUnmatchedTagUid(result.nfc_tag_uid || null);
      if (result.qidi_data) {
        setUnmatchedQidiData(result.qidi_data);
      } else if (result.tag_data) {
        setUnmatchedTagData(result.tag_data);
      }
    }
  }, [nfcReadMutation, navigate]);

  const handleBrowserScan = useCallback(async () => {
    if (!window.NDEFReader) {
      setBrowserError(t("nfc.error.not_supported"));
      return;
    }

    setBrowserScanning(true);
    setBrowserError(null);
    setUnmatchedTagData(null);

    try {
      const reader = new window.NDEFReader();
      const controller = new AbortController();

      reader.onreading = (event: NDEFReadingEvent) => {
        controller.abort();
        setBrowserScanning(false);

        // Look through NDEF records for a TigerTag external type, Spoolman URI, or ID
        for (const record of event.message.records) {
          // Check for TigerTag NDEF external type record
          if (record.recordType === "tigertag.io:maker" && record.data) {
            try {
              const tagData = decodeTigerTag(record.data.buffer as ArrayBuffer);
              if (isTigerTag(tagData.id_tigertag) && tagData.id_product > 0) {
                // Convert RGBA to hex string
                const colorHex = [tagData.color_r, tagData.color_g, tagData.color_b]
                  .map((c) => c.toString(16).padStart(2, "0"))
                  .join("");
                // Derive diameter from id_diameter
                const diameterMm = tagData.id_diameter === 1 ? 1.75 : tagData.id_diameter === 2 ? 2.85 : 0;

                setUnmatchedTagData({
                  id_tigertag: tagData.id_tigertag,
                  id_product: tagData.id_product,
                  id_material: tagData.id_material,
                  id_diameter: tagData.id_diameter,
                  id_brand: tagData.id_brand,
                  color_hex: colorHex,
                  weight: tagData.weight,
                  nozzle_temp: tagData.nozzle_temp,
                  bed_temp: tagData.bed_temp,
                  drying_temp: tagData.drying_temp,
                  drying_duration: tagData.drying_duration,
                  timestamp: tagData.timestamp,
                  user_message: tagData.user_message,
                  diameter_mm: diameterMm,
                });
                return;
              }
            } catch {
              // Failed to decode, fall through to other record types
            }
          }

          if (record.recordType === "url" || record.recordType === "text") {
            const decoder = new TextDecoder(record.encoding || "utf-8");
            const text = record.data ? decoder.decode(record.data) : "";

            // Check for spoolman:s-{id} format
            const spoolmanMatch = text.match(/web\+spoolman:s-(\d+)/);
            if (spoolmanMatch) {
              setVisible(false);
              navigate(`/spool/show/${spoolmanMatch[1]}`);
              return;
            }

            // Check for URL format
            const urlMatch = text.match(/\/spool\/show\/(\d+)/);
            if (urlMatch) {
              setVisible(false);
              navigate(`/spool/show/${urlMatch[1]}`);
              return;
            }
          }
        }

        setBrowserError(t("nfc.no_match"));
      };

      reader.onreadingerror = () => {
        controller.abort();
        setBrowserScanning(false);
        setBrowserError(t("nfc.error.read_failed"));
      };

      await reader.scan({ signal: controller.signal });
    } catch (error) {
      setBrowserScanning(false);
      if (error instanceof DOMException && error.name === "NotAllowedError") {
        setBrowserError(t("nfc.error.permission_denied"));
      } else {
        setBrowserError(t("nfc.error.read_failed"));
      }
    }
  }, [t, navigate]);

  const handleCreateFromTag = useCallback(async () => {
    if (!unmatchedTagData && !unmatchedQidiData) return;

    let result;
    if (unmatchedQidiData && unmatchedTagFormat === "qidi") {
      result = await createFromTagMutation.mutateAsync({
        tag_type: "qidi",
        material_code: unmatchedQidiData.material_code,
        color_code: unmatchedQidiData.color_code,
        nfc_tag_uid: unmatchedTagUid || undefined,
      });
    } else if (unmatchedTagData) {
      result = await createFromTagMutation.mutateAsync({
        id_product: unmatchedTagData.id_product,
        id_material: unmatchedTagData.id_material,
        id_diameter: unmatchedTagData.id_diameter,
        id_brand: unmatchedTagData.id_brand,
        color_hex: unmatchedTagData.color_hex,
        weight: unmatchedTagData.weight,
        nozzle_temp: unmatchedTagData.nozzle_temp,
        bed_temp: unmatchedTagData.bed_temp,
        drying_temp: unmatchedTagData.drying_temp,
        drying_duration: unmatchedTagData.drying_duration,
        diameter_mm: unmatchedTagData.diameter_mm,
      });
    } else {
      return;
    }

    if (result.success && result.spool_id) {
      setVisible(false);
      setUnmatchedTagData(null);
      setUnmatchedQidiData(null);
      navigate(`/spool/show/${result.spool_id}`);
    }
  }, [unmatchedTagData, unmatchedQidiData, unmatchedTagFormat, unmatchedTagUid, createFromTagMutation, navigate]);

  // Don't show the button if neither server NFC nor Web NFC is available
  if (!serverEnabled && !webNfcAvailable) {
    return null;
  }

  return (
    <>
      <FloatButton
        type="primary"
        onClick={() => setVisible(true)}
        icon={<WifiOutlined />}
        shape="circle"
        style={{ insetInlineEnd: 74 }}
      />
      <Modal
        open={visible}
        destroyOnClose
        onCancel={() => {
          setVisible(false);
          setBrowserScanning(false);
          setBrowserError(null);
          setUnmatchedTagData(null);
          setUnmatchedQidiData(null);
          setUnmatchedTagUid(null);
          setUnmatchedTagFormat(null);
        }}
        footer={null}
        title={t("nfc.scan_title")}
      >
        <Space direction="vertical" style={{ width: "100%" }} size="middle">
          <Text>{t("nfc.scan_description")}</Text>

          <Segmented
            block
            options={[
              { label: t("nfc.mode_server"), value: "server", disabled: !serverEnabled },
              { label: t("nfc.mode_browser"), value: "browser", disabled: !webNfcAvailable },
            ]}
            value={mode}
            onChange={(value) => setMode(value as "browser" | "server")}
          />

          {mode === "server" && (
            <Space direction="vertical" style={{ width: "100%" }} align="center">
              <Button
                type="primary"
                onClick={handleServerRead}
                loading={nfcReadMutation.isPending}
                size="large"
              >
                {nfcReadMutation.isPending ? t("nfc.reading") : t("nfc.scan_title")}
              </Button>
              {nfcReadMutation.isSuccess && !nfcReadMutation.data?.spool_id && !unmatchedTagData && (
                <Alert
                  type="warning"
                  message={nfcReadMutation.data?.message || t("nfc.no_match")}
                  showIcon
                />
              )}
              {nfcReadMutation.isError && (
                <Alert type="error" message={t("nfc.error.read_failed")} showIcon />
              )}
            </Space>
          )}

          {mode === "browser" && (
            <Space direction="vertical" style={{ width: "100%" }} align="center">
              {browserScanning ? (
                <Spin tip={t("nfc.place_tag")}>
                  <div style={{ padding: 50 }} />
                </Spin>
              ) : (
                <Button type="primary" onClick={handleBrowserScan} size="large">
                  {t("nfc.scan_title")}
                </Button>
              )}
              {browserError && !unmatchedTagData && (
                <Alert type="error" message={browserError} showIcon />
              )}
            </Space>
          )}

          {/* Show tag data and create button when no spool matched */}
          {(unmatchedTagData || unmatchedQidiData) && (
            <Space direction="vertical" style={{ width: "100%" }} size="middle">
              <Alert type="info" message={t("nfc.create_from_tag_description")} showIcon />
              {unmatchedQidiData ? (
                <QidiTagDataSummary qidiData={unmatchedQidiData} t={t} />
              ) : unmatchedTagData ? (
                <TagDataSummary tagData={unmatchedTagData} t={t} />
              ) : null}
              <Button
                type="primary"
                onClick={handleCreateFromTag}
                loading={createFromTagMutation.isPending}
                block
              >
                {createFromTagMutation.isPending ? t("nfc.creating_spool") : t("nfc.create_from_tag")}
              </Button>
              {createFromTagMutation.isSuccess && createFromTagMutation.data?.success && (
                <Alert type="success" message={t("nfc.create_success")} showIcon />
              )}
              {(createFromTagMutation.isError ||
                (createFromTagMutation.isSuccess && !createFromTagMutation.data?.success)) && (
                <Alert
                  type="error"
                  message={createFromTagMutation.data?.message || t("nfc.create_error")}
                  showIcon
                />
              )}
            </Space>
          )}
        </Space>
      </Modal>
    </>
  );
};

export default NfcScannerModal;
